### ISSUE TITLE
Server not working?

### ISSUE THREAD

**Issue by mxft** [Flxma/liliths-throne-multiplayer#1]
Nothing happens when you launch the server. But javaw.exe process appears in the task manager.

Tested on Windows 10 20H1.

**Comment by Flxma** [comment]
Hi, that might be the case because this server is a command line program. 
I will include a .bat file in the next release, that you can just double-click to open the server

**Comment by mxft** [comment]
> Hi, that might be the case because this server is a command line program. I will include a .bat file in the next release, that you can just double-click to open the server

Oh, thank you. Didn't know it's command-line due to lack of documentation.

**Comment by Flxma** [comment]
Yeah, sorry about this...  I started all of this as a hobby project and havent done a good job of documenting stufff heh. I'll try to change that though
